services:
  factorx-db:
    container_name: factorx-db
    image: postgres:latest
    env_file: .env.local
    ports:
      - "5432:5432"
    volumes:
      #      - ./db_data:/var/lib/postgresql/data
      - ./init_db:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      timeout: 5s
      interval: 2s
      retries: 200
  redis:
    image: "redis:alpine"
    hostname: redis
    command: redis-server
    ports:
      - "6379:6379"
    expose:
      - "6379"
#  redis-commander:
#    image: rediscommander/redis-commander:latest
#    restart: always
#    environment:
#      REDIS_HOSTS: redis
#      REDIS_HOST: redis
#      REDIS_PORT: redis:6379
#      REDIS_PASSWORD: ${REDIS_PASSWORD}
#      HTTP_USER: root
#      HTTP_PASSWORD: root
#    ports:
#      - "8081:8081"
#    volumes:
#      - redis-data:/data
#      - redis-conf:/usr/local/etc/redis/redis.conf
#  factorx-app:
#    build:
#      context: .
#      dockerfile: Dockerfile-local
#    env_file: .env.local
#    ports:
#      - '8080:8080'
#    depends_on:
#     factorx-db:
#        condition: service_healthy
