spring:
  datasource:
    url: jdbc:mysql://localhost:3306
    username: root
    password: 123456
    manager:
      url: ${spring.datasource.url}/manager?createDatabaseIfNotExist=true
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  liquibase:
    admin:
      change-log: classpath:/db/admin/master.xml
    tenant:
      change-log: classpath:/db/tenants/master.xml
