spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/factorx_dev?currentSchema=registry
    username: factorx_dev
    password: factorx_dev
  liquibase:
    registry:
      change-log: classpath:/db/registry/master.yml
    tenant:
      change-log: classpath:/db/tenants/master.yml
  data:
    jdbc:
      repositories:
        enabled: true
    redis:
      host: localhost
      port: 6379

server:
  port: 8082

logging:
  level:
    org:
      springframework:
        jdbc: debug
