spring:
  datasource:
    url: jdbc:mysql://localhost:3306/manager?createDatabaseIfNotExist=true
    username: root
    password: 123456
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  liquibase:
    admin:
      change-log: classpath:/db/admin/master.xml
    tenant:
      change-log: classpath:/db/tenants/master.xml
